### ISSUE TITLE
Generating a GP4 for a patch with gengp4_patch.exe modifies param.sfo and sets it as game application

### ISSUE THREAD

**Issue by EnekoT2001** [CyB1K/PS4-Fake-PKG-Tools-3.87#16]
When generating a gp4 with gengp4_patch.exe, it modifies the param.sfo setting the application type as game application instead of application patch, when using orbis-pub-gen.exe to generate a pkg using the gp4 generated witth it, it's impossible to build an update pkg bc gengp4 treated it as a full game and not a patch so it generates a full game .pkg instead.

**Comment by CyB1K** [comment]
If you did read the instructions on how to build pkgs properly, you wouldnt have this issue

**Comment by CyB1K** [comment]
2. After extracting rename the folder from Image0 to CUSAXXXXX-app or CUSAXXXXX-patch, accordingly.

**Comment by EnekoT2001** [comment]
I see, thank you for the help, the programs were so straightforward that I just started using them and I didn't think the name of the folder could mess stuff up like this since there was a dedicated gengp4 program for patches but yeah I should've checked the readme, it totally slipped my mind. so sorry to bother u!

**Comment by danlopesmusic-code** [comment]
Always keep a backup of the original param.sfo file to replace for the param.sfo generated by gengp4 after creating the gp4 file or you gonna have this issue.
